В первом таске нам нужно сделать dataset по активности молекул COX-2.

In [1]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdmolops

In [2]:
df = pd.read_csv('input_file.csv', sep=';')
df

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL70104,NaN,NaN,364.46,0.0,3.49,3,CC1(C)OC(=O)C(OC2CCCCC2)=C1c1ccc(S(C)(=O)=O)cc1,IC50,'=',...,CHEMBL1131821,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,0.04
1,CHEMBL96098,NaN,NaN,372.88,0.0,4.43,34,CCc1ccc(-c2ncc(Cl)cc2-c2ccc(S(C)(=O)=O)cc2)cn1,IC50,'=',...,CHEMBL1130609,1,Scientific Literature,Bioorg Med Chem Lett,1998.0,NaN,NaN,NaN,NaN,1.70
2,CHEMBL97179,NaN,NaN,413.90,1.0,5.19,5,CCCCOC(=O)Cc1c(C)n(C(=O)c2ccc(Cl)cc2)c2ccc(OC)...,IC50,'=',...,CHEMBL1133457,1,Scientific Literature,J Med Chem,2000.0,NaN,NaN,NaN,NaN,0.05
3,CHEMBL6,INDOMETHACIN,4.0,357.79,0.0,3.93,Indomethacin,COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1,IC50,'<',...,CHEMBL1131754,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,200.00
4,CHEMBL355781,NaN,NaN,390.46,0.0,4.25,21,CS(=O)(=O)c1ccc(-c2csc(CC(=O)O)c2-c2ccc(F)cc2)cc1,IC50,'>',...,CHEMBL1128908,1,Scientific Literature,Bioorg Med Chem Lett,1996.0,CHEMBL3308860,NaN,NaN,NaN,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7974,CHEMBL118,CELECOXIB,4.0,381.38,0.0,3.51,Celecoxib,Cc1ccc(-c2cc(C(F)(F)F)nn2-c2ccc(S(N)(=O)=O)cc2...,IC50,'=',...,CHEMBL5370546,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,0.04
7975,CHEMBL521,IBUPROFEN,4.0,206.28,0.0,3.07,Motrin,CC(C)Cc1ccc(C(C)C(=O)O)cc1,IC50,'=',...,CHEMBL5370523,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,370.00
7976,CHEMBL139,DICLOFENAC,4.0,296.15,0.0,4.36,DIF,O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl,IC50,'=',...,CHEMBL5233249,1,Scientific Literature,Eur J Med Chem,2020.0,NaN,DOSE = 10.0 microM,INHIBITOR,NaN,1.10
7977,CHEMBL121626,TOLFENAMIC ACID,4.0,261.71,0.0,4.09,Tolfenamic acid,Cc1c(Cl)cccc1Nc1ccccc1C(=O)O,IC50,'=',...,CHEMBL5032522,1,Scientific Literature,Eur J Med Chem,2021.0,NaN,TIME = 0.2 hr,INHIBITOR,NaN,0.88
7978,CHEMBL571,KETOPROFEN,4.0,254.29,0.0,3.11,Orudis,CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1,IC50,'=',...,CHEMBL5370523,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,26.00

Удаляем Standard Value = NaN строки

In [3]:
df = df.dropna(subset=['Standard Value'])
df = df.dropna(subset=['Standard Units'])
df

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL70104,NaN,NaN,364.46,0.0,3.49,3,CC1(C)OC(=O)C(OC2CCCCC2)=C1c1ccc(S(C)(=O)=O)cc1,IC50,'=',...,CHEMBL1131821,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,0.04
1,CHEMBL96098,NaN,NaN,372.88,0.0,4.43,34,CCc1ccc(-c2ncc(Cl)cc2-c2ccc(S(C)(=O)=O)cc2)cn1,IC50,'=',...,CHEMBL1130609,1,Scientific Literature,Bioorg Med Chem Lett,1998.0,NaN,NaN,NaN,NaN,1.70
2,CHEMBL97179,NaN,NaN,413.90,1.0,5.19,5,CCCCOC(=O)Cc1c(C)n(C(=O)c2ccc(Cl)cc2)c2ccc(OC)...,IC50,'=',...,CHEMBL1133457,1,Scientific Literature,J Med Chem,2000.0,NaN,NaN,NaN,NaN,0.05
3,CHEMBL6,INDOMETHACIN,4.0,357.79,0.0,3.93,Indomethacin,COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1,IC50,'<',...,CHEMBL1131754,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,200.00
4,CHEMBL355781,NaN,NaN,390.46,0.0,4.25,21,CS(=O)(=O)c1ccc(-c2csc(CC(=O)O)c2-c2ccc(F)cc2)cc1,IC50,'>',...,CHEMBL1128908,1,Scientific Literature,Bioorg Med Chem Lett,1996.0,CHEMBL3308860,NaN,NaN,NaN,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7974,CHEMBL118,CELECOXIB,4.0,381.38,0.0,3.51,Celecoxib,Cc1ccc(-c2cc(C(F)(F)F)nn2-c2ccc(S(N)(=O)=O)cc2...,IC50,'=',...,CHEMBL5370546,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,0.04
7975,CHEMBL521,IBUPROFEN,4.0,206.28,0.0,3.07,Motrin,CC(C)Cc1ccc(C(C)C(=O)O)cc1,IC50,'=',...,CHEMBL5370523,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,370.00
7976,CHEMBL139,DICLOFENAC,4.0,296.15,0.0,4.36,DIF,O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl,IC50,'=',...,CHEMBL5233249,1,Scientific Literature,Eur J Med Chem,2020.0,NaN,DOSE = 10.0 microM,INHIBITOR,NaN,1.10
7977,CHEMBL121626,TOLFENAMIC ACID,4.0,261.71,0.0,4.09,Tolfenamic acid,Cc1c(Cl)cccc1Nc1ccccc1C(=O)O,IC50,'=',...,CHEMBL5032522,1,Scientific Literature,Eur J Med Chem,2021.0,NaN,TIME = 0.2 hr,INHIBITOR,NaN,0.88
7978,CHEMBL571,KETOPROFEN,4.0,254.29,0.0,3.11,Orudis,CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1,IC50,'=',...,CHEMBL5370523,1,Scientific Literature,Eur J Med Chem,2023.0,NaN,NaN,INHIBITOR,NaN,26.00

Приводим к одному единице измерения и удаляем NaN единицы измерения. За основу возьмем nM

In [4]:
df['Standard Units'].unique().tolist()

['nM', 'ug.mL-1', 'ug', '%']

In [5]:
df = df.drop_duplicates(subset=['Molecule ChEMBL ID']).reset_index(drop=True)
df

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL70104,NaN,NaN,364.46,0.0,3.49,3,CC1(C)OC(=O)C(OC2CCCCC2)=C1c1ccc(S(C)(=O)=O)cc1,IC50,'=',...,CHEMBL1131821,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,0.04
1,CHEMBL96098,NaN,NaN,372.88,0.0,4.43,34,CCc1ccc(-c2ncc(Cl)cc2-c2ccc(S(C)(=O)=O)cc2)cn1,IC50,'=',...,CHEMBL1130609,1,Scientific Literature,Bioorg Med Chem Lett,1998.0,NaN,NaN,NaN,NaN,1.70
2,CHEMBL97179,NaN,NaN,413.90,1.0,5.19,5,CCCCOC(=O)Cc1c(C)n(C(=O)c2ccc(Cl)cc2)c2ccc(OC)...,IC50,'=',...,CHEMBL1133457,1,Scientific Literature,J Med Chem,2000.0,NaN,NaN,NaN,NaN,0.05
3,CHEMBL6,INDOMETHACIN,4.0,357.79,0.0,3.93,Indomethacin,COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1,IC50,'<',...,CHEMBL1131754,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,200.00
4,CHEMBL355781,NaN,NaN,390.46,0.0,4.25,21,CS(=O)(=O)c1ccc(-c2csc(CC(=O)O)c2-c2ccc(F)cc2)cc1,IC50,'>',...,CHEMBL1128908,1,Scientific Literature,Bioorg Med Chem Lett,1996.0,CHEMBL3308860,NaN,NaN,NaN,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5121,CHEMBL487933,NaN,NaN,456.71,1.0,7.23,8,CC1(C)[C@@H](O)CC[C@]2(C)[C@H]3CC=C4[C@@H]5C[C...,IC50,'>',...,CHEMBL4414666,1,Scientific Literature,J Nat Prod,2019.0,CHEMBL4106362,NaN,NaN,NaN,40.00
5122,CHEMBL189171,ACEMETACIN,4.0,415.83,0.0,3.47,19,COc1ccc2c(c1)c(CC(=O)OCC(=O)O)c(C)n2C(=O)c1ccc...,IC50,'=',...,CHEMBL5344475,1,Scientific Literature,RSC Med Chem,2024.0,NaN,TIME = 0.25 hr,INHIBITOR,NaN,10.00
5123,CHEMBL4515706,NaN,NaN,394.51,1.0,6.00,8,COc1ccc(/C=C/c2c(CC=C(C)C)c(O)cc(O)c2CC=C(C)C)...,IC50,'=',...,CHEMBL4339252,1,Scientific Literature,J Nat Prod,2019.0,NaN,NaN,NaN,NaN,14.70
5124,CHEMBL704,MESALAMINE,4.0,153.14,0.0,0.67,mesalazine,Nc1ccc(O)c(C(=O)O)c1,IC50,'=',...,CHEMBL4406809,1,Scientific Literature,Eur J Med Chem,2019.0,NaN,NaN,NaN,NaN,7.53
5125,CHEMBL121626,TOLFENAMIC ACID,4.0,261.71,0.0,4.09,Tolfenamic acid,Cc1c(Cl)cccc1Nc1ccccc1C(=O)O,IC50,'=',...,CHEMBL5032522,1,Scientific Literature,Eur J Med Chem,2021.0,NaN,TIME = 0.2 hr,INHIBITOR,NaN,0.88

Проверка валидности SMILES

In [6]:
def valid_smiles(smiles):
    try:
        # Попытка создать молекулу из SMILES 
        mol = Chem.MolFromSmiles(smiles, sanitize=False)
        if mol is None:
            return False
        rdmolops.SanitizeMol(mol)
        return True
    except Exception:
        return False

mask = df['Smiles'].apply(valid_smiles)
df_valid = df[mask].reset_index(drop=True)
df_valid

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL70104,NaN,NaN,364.46,0.0,3.49,3,CC1(C)OC(=O)C(OC2CCCCC2)=C1c1ccc(S(C)(=O)=O)cc1,IC50,'=',...,CHEMBL1131821,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,0.04
1,CHEMBL96098,NaN,NaN,372.88,0.0,4.43,34,CCc1ccc(-c2ncc(Cl)cc2-c2ccc(S(C)(=O)=O)cc2)cn1,IC50,'=',...,CHEMBL1130609,1,Scientific Literature,Bioorg Med Chem Lett,1998.0,NaN,NaN,NaN,NaN,1.70
2,CHEMBL97179,NaN,NaN,413.90,1.0,5.19,5,CCCCOC(=O)Cc1c(C)n(C(=O)c2ccc(Cl)cc2)c2ccc(OC)...,IC50,'=',...,CHEMBL1133457,1,Scientific Literature,J Med Chem,2000.0,NaN,NaN,NaN,NaN,0.05
3,CHEMBL6,INDOMETHACIN,4.0,357.79,0.0,3.93,Indomethacin,COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1,IC50,'<',...,CHEMBL1131754,1,Scientific Literature,Bioorg Med Chem Lett,1999.0,NaN,NaN,NaN,NaN,200.00
4,CHEMBL355781,NaN,NaN,390.46,0.0,4.25,21,CS(=O)(=O)c1ccc(-c2csc(CC(=O)O)c2-c2ccc(F)cc2)cc1,IC50,'>',...,CHEMBL1128908,1,Scientific Literature,Bioorg Med Chem Lett,1996.0,CHEMBL3308860,NaN,NaN,NaN,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5120,CHEMBL487933,NaN,NaN,456.71,1.0,7.23,8,CC1(C)[C@@H](O)CC[C@]2(C)[C@H]3CC=C4[C@@H]5C[C...,IC50,'>',...,CHEMBL4414666,1,Scientific Literature,J Nat Prod,2019.0,CHEMBL4106362,NaN,NaN,NaN,40.00
5121,CHEMBL189171,ACEMETACIN,4.0,415.83,0.0,3.47,19,COc1ccc2c(c1)c(CC(=O)OCC(=O)O)c(C)n2C(=O)c1ccc...,IC50,'=',...,CHEMBL5344475,1,Scientific Literature,RSC Med Chem,2024.0,NaN,TIME = 0.25 hr,INHIBITOR,NaN,10.00
5122,CHEMBL4515706,NaN,NaN,394.51,1.0,6.00,8,COc1ccc(/C=C/c2c(CC=C(C)C)c(O)cc(O)c2CC=C(C)C)...,IC50,'=',...,CHEMBL4339252,1,Scientific Literature,J Nat Prod,2019.0,NaN,NaN,NaN,NaN,14.70
5123,CHEMBL704,MESALAMINE,4.0,153.14,0.0,0.67,mesalazine,Nc1ccc(O)c(C(=O)O)c1,IC50,'=',...,CHEMBL4406809,1,Scientific Literature,Eur J Med Chem,2019.0,NaN,NaN,NaN,NaN,7.53
5124,CHEMBL121626,TOLFENAMIC ACID,4.0,261.71,0.0,4.09,Tolfenamic acid,Cc1c(Cl)cccc1Nc1ccccc1C(=O)O,IC50,'=',...,CHEMBL5032522,1,Scientific Literature,Eur J Med Chem,2021.0,NaN,TIME = 0.2 hr,INHIBITOR,NaN,0.88